### ISSUE TITLE
Add ∞-AE and EASE?

### ISSUE THREAD

**Issue by noveens** [recsys-benchmark/DaisyRec-v2.0#12]
Hello code maintainers,

Thanks for your efforts towards equitable benchmarking of different recommender systems! I believe it's really helpful for the community :)

As a suggestion -- is it possible to somehow include [∞-AE](https://arxiv.org/pdf/2206.02626.pdf) (with [code](https://github.com/noveens/infinite_ae_cf)) and [EASE](https://arxiv.org/abs/1905.03375) in the comparisons? Shouldn't take much time since both of them have only a single hyper-parameter. If not, that's fine too!

Best,
Noveen

**Comment by hyllll** [comment]
Thanks for your suggestion. We will try our best to include the two methods asap.
